### ISSUE TITLE
All use of `" null"` is replaced with `""` in an RFC's content

### ISSUE THREAD

**Issue by bertdeblock** [emberjs/rfcs-tooling#14]
Some examples:
- https://github.com/emberjs/rfcs/pull/875/files#diff-007eb250a8f0d75326107ccaa7b2047799e14adad7a9e4998df8e16f40f1bb6dR625
- https://github.com/emberjs/rfcs/pull/874/files#diff-13c3755669f99e14f510c8d659db8c77483173755382d5aa5e97be98058e4e2cR287
- https://github.com/emberjs/rfcs/pull/868/files#diff-5cd13663f87b395c0da8e155fc1e683f0aebc559ef4616731f02551481e845beR320

This happens here:
https://github.com/emberjs/rfcs-tooling/blob/main/lib/frontmatter-updater.js#L16

**Comment by kategengler** [comment]
Thanks for filing an issue! The replacement of null in that spot is because the `frontmatter` output turns any empty fields into `null`. This needs to run on just the frontmatter, not the entire doc.
