### ISSUE TITLE
Include PR Title in Advancement RFCs

### ISSUE THREAD

**Issue by jenweber** [emberjs/rfcs-tooling#16]
I am interested to implement this, but would like a clue of where you think I should start. Here are the options I thought of so far:

- Write a node script that grabs the first h1 from the markdown, and output it as a variable available to GitHub Actions, then thread that variable through (more work/complexity, more readable)
- Use the "path" var already available in the actions. Add that to PR titles and call it good enough. (Less work, not as readable)

The problems I am trying to solve are:
- When I look at the list of PRs open in the RFCs repo and I want to find a specific advancement RFC, I need to look up the number first. I cannot search for any keywords from the RFC.
- when I look at my GitHub notifications, I can't tell which PR is being advanced until I click into it.

**Comment by kategengler** [comment]
Hi @jenweber!

I'm afraid I beat you to it. I'm not ready to PR just yet but getting close here https://github.com/emberjs/rfcs-tooling/tree/kg-add-title

I went with using the markdown AST to grab the h1 text contents.

**Comment by jenweber** [comment]
Yay, thank you!
